# -*- coding: utf-8 -*-
"""retrieval_agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10Yp7NcUcEznz0tcRwOl3jOfneA5wov3J

Retrieval Agent for Indonesian Job Search
Collection name: indonesian_job_v2

This agent retrieves job information from Qdrant vector database
and will work as part of a multi-agent system orchestrated by supervisor.
"""

import os
from typing import Optional

from langchain_qdrant import QdrantVectorStore
from langchain_core.tools import tool
from langchain_openai import ChatOpenAI
from langchain.agents import create_agent

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

# Initialize Qdrant vectorstore
vectorstore: Optional[QdrantVectorStore] = None


# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# CREATE RETRIEVAL TOOL
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

@tool
def search_indonesian_jobs(query: str) -> str:
    """
    Search and retrieve information about Indonesian job postings from the database.

    Use this tool to answer questions about:
    - Job positions and titles
    - Company names and information
    - Salary ranges and compensation
    - Job locations (cities/regions in Indonesia)
    - Work types (remote, on-site, hybrid)
    - Job qualifications and requirements
    - Job descriptions and responsibilities

    Args:
        query (str): The search query in Indonesian or English.
                    Examples: "data scientist Jakarta", "gaji software engineer",
                    "lowongan remote work"

    Returns:
        str: Formatted search results containing relevant job information
    """
    try:
        # Retrieve relevant documents using the retriever
        retriever = vectorstore.as_retriever(
            search_type="similarity", search_kwargs={"k": 5}
        )
        docs = retriever.invoke(query)

        if not docs:
            return "Maaf, tidak ditemukan informasi lowongan kerja yang relevan dengan pertanyaan Anda."

        # Format results
        results = [f"Ditemukan {len(docs)} lowongan kerja yang relevan:\n"]

        for i, doc in enumerate(docs, 1):
            metadata = doc.metadata
            content = doc.page_content

            # Create structured output
            job_info = f"""
{'='*60}
Lowongan {i}:
{'='*60}
Posisi: {metadata.get('job_title', 'N/A')}
Perusahaan: {metadata.get('company_name', 'N/A')}
Lokasi: {metadata.get('location', 'N/A')}
Gaji: {metadata.get('salary', 'N/A')}
Tipe Kerja: {metadata.get('work_type', 'N/A')}

Deskripsi:
{content[:400]}{'...' if len(content) > 400 else ''}
"""
            results.append(job_info)

        return "\n".join(results)

    except Exception as e:
        error_msg = f"Terjadi kesalahan saat mencari data: {str(e)}"
        print(error_msg)
        import traceback
        traceback.print_exc()
        return error_msg

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# CREATE RETRIEVAL AGENT
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

retrieval_prompt='''
You are a professional Indonesian job search assistant specialized in helping users find relevant job opportunities in Indonesia.

YOUR PRIMARY OBJECTIVE:
Help users discover and understand job listings by retrieving accurate information from the job database.

MANDATORY INSTRUCTIONS:

1. TOOL USAGE (CRITICAL):
   - You MUST use the 'search_indonesian_jobs' tool for ANY job-related query
   - NEVER provide job information without using the tool first
   - Call the tool with specific, relevant search terms based on the user's question

2. RESPONSE LANGUAGE:
   - ALL responses MUST be in Bahasa Indonesia (Indonesian language)
   - Use polite and professional tone (formal Indonesian business language)
   - Maintain consistency in language throughout the conversation

3. INFORMATION ACCURACY:
   - Provide ONLY information retrieved from the tool results
   - Do NOT hallucinate or make up job listings, salaries, or company information
   - If the tool returns no results, acknowledge this clearly

4. HANDLING NO RESULTS:
   - If search returns empty or irrelevant results, suggest the user to:
     a) Use more specific keywords
     b) Try different job titles or synonyms
     c) Broaden the search criteria (e.g., remove location filters)

5. RESPONSE FORMATTING:
   - Structure answers in clear, scannable format
   - Use bullet points or numbered lists when presenting multiple jobs
   - Separate different job listings clearly
   - Highlight key information: job title, company, location, salary

6. SALARY QUERIES:
   - If salary information is available in tool results, provide it exactly as returned
   - If salary range exists, present both minimum and maximum values
   - If salary is not specified, state "Gaji tidak disebutkan" (Salary not specified)
   - NEVER estimate or guess salary figures

7. QUALIFICATION QUERIES:
   - Extract qualification requirements directly from job descriptions
   - Categorize into: education, experience, technical skills, soft skills
   - If qualifications are not clear, state what information is available

EXAMPLE QUERIES YOU CAN HANDLE:
- "Cari lowongan data scientist di Jakarta"
- "Berapa gaji rata-rata software engineer?"
- "Perusahaan apa saja yang buka lowongan remote?"
- "Apa kualifikasi untuk posisi product manager?"
- "Lowongan fresh graduate di Bandung"

WORKFLOW FOR EVERY USER QUERY:
Step 1: Identify the search intent (job title, location, company, etc.)
Step 2: Call search_indonesian_jobs tool with appropriate keywords
Step 3: Parse and analyze the tool results
Step 4: Format and present the information in clear Indonesian
Step 5: Offer to help with follow-up questions

CRITICAL RULE: Always search first, answer second. Never skip the tool usage.'''

# Create retrieval agent
job_retrieval_agent = create_agent(
    model=ChatOpenAI(
        model="gpt-4o-mini",
        api_key=OPENAI_API_KEY,
    ),
    tools=[search_indonesian_jobs],
    system_prompt=retrieval_prompt,
    name="job_retrieval_agent",
)

def ask_job_question(
    question: str,
    history: str,
    session_id: str,
    verbose: bool = True,
) -> str:
    """
    Helper function to query the job retrieval agent.

    Args:
        question (str): User's question
        history (str): Previous conversation history
        session_id (str): Unique identifier for the conversation
        verbose (bool): Print detailed execution steps

    Returns:
        str: Agent's response
    """
    if verbose:
        print(f"[{session_id}] {'='*70}")
        print(f"[{session_id}] Question: {question}")
        print(f"[{session_id}] {'='*70}")

    response = job_retrieval_agent.invoke(
        {"messages": [{"role": "user", "content": question}]}
    )

    answer = response['messages'][-1].content

    if verbose:
        print(f"[{session_id}] Answer:\n{answer}")
        print(f"[{session_id}] {'='*70}")

    return answer
